---
name: 'Release Schedule Block plugin'

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: PHP Composer dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ github.token }}
      
      - id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      
      - name: Install composer deps
        shell: bash
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      
      - name: Install node deps
        shell: bash
        run: yarn install --frozen-lockfile
      
      - name: Build assets
        shell: bash
        run: yarn build:prod

      - name: Generate release folder
        shell: bash
        run: rsync -r --exclude .git --exclude .github --exclude .gitignore --exclude .editorconfig --exclude .nvmrc --exclude composer.json --exclude composer.lock --exclude package.json --exclude postcss.config.js --exclude tsconfig.json --exclude webpack.config.js --exclude yarn.lock . ./schedule-block
          
      - name: Archive Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r schedule-block.zip schedule-block

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            schedule-block.zip
